### ISSUE TITLE
Strange behaviour with Tahoe mountpoint and Plex/Emby services

### ISSUE THREAD

**Issue by dimitribellini** [pv/tahoestaticfs#4]
First of all, thanks very much for your Tahoe FS implementation.
I have tested your tahoestaticfs with a small enviroment based on raspberry and everything is working ok with a mount point and classic "cp/rm/etc" command line tools but as soon a start a program called Plex or Emby (Media Server solutions) my fuse mount point seems locked.
I could send you some debug line if you need.
Thank so much

**Comment by dimitribellini** [comment]
I have grab some debug info:
---
2016-11-23 07:34:56,663 tahoestaticfs[1845]: /mnt/extra DEBUG: Failed operation
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/tahoestaticfs/staticfs.py", line 22, in wrapper
    return func(*a, **kw)
  File "build/bdist.linux-x86_64/egg/tahoestaticfs/staticfs.py", line 226, in getattr
    info = self.cache.get_attr(upath, self.io)
  File "build/bdist.linux-x86_64/egg/tahoestaticfs/cachedb.py", line 368, in get_attr
    info = dir.get_child_attr(ubasename(upath))
  File "build/bdist.linux-x86_64/egg/tahoestaticfs/cachedb.py", line 649, in get_child_attr
    return self.inode.get_child_attr(childname)
  File "build/bdist.linux-x86_64/egg/tahoestaticfs/cachedb.py", line 1000, in get_child_attr
    raise IOError(errno.ENOENT, "no such entry")
IOError: [Errno 2] no such entry
   unique: 1575, error: -2 (No such file or directory), outsize: 16
---
Thanks for the help
